var monjiImages = [
    {en:"monji-of-changhua-county", md:"彰化縣章"},
    {en:"monji-of-changhua-city", md:"彰化市章"},
    {en:"monji-of-chiayi-city", md:"嘉義市章"},
    {en:"monji-of-chiayi-county", md:"嘉義縣章"},
    {en:"monji-of-puzi-city", md:"朴子市章"},
    {en:"monji-of-taibou-city", md:"太保市章"},
    {en:"monji-of-hsinchu-city", md:"新竹市章"},
    {en:"monji-of-hsinchu-county", md:"新竹縣章"},
    {en:"monji-of-zhubei-city", md:"竹北市章"},
    {en:"monji-of-hualian-county", md:"花蓮縣章"},
    {en:"monji-of-keelung-city", md:"基隆市章"},
    {en:"monji-of-miaoli-county", md:"苗栗縣章"},
    {en:"monji-of-nantou-county", md:"南投縣章"},
    {en:"monji-of-new-taipei-city", md:"新北市章"},
    {en:"monji-of-penghu-county", md:"澎湖縣章"},
    {en:"monji-of-pingtung-county", md:"屏東縣章"},
    {en:"monji-of-taichung-city", md:"台中市章"},
    {en:"monji-of-tainan-city", md:"台南市章"},
    {en:"monji-of-west-central-tainan-city", md:"台南市中西區章"},
    {en:"monji-of-taipei-city", md:"台北市章"},
    {en:"monji-of-taitung-county", md:"台東縣章"},
    {en:"monji-of-takaohsiung-city", md:"高雄市章"},
    {en:"monji-of-taoyuan-city", md:"桃園市章"},
    {en:"monji-of-yilan-county", md:"宜蘭縣章"},
    {en:"monji-of-yunlin-county", md:"雲林縣章"},
    {en:"monji-of-taixi-yunlin-county", md:"雲林縣台西鄉章"}
];
var monjiConfig = {
    dir: "/images/monjis/",
    container: "#monji-ctn",
    type: "flag",
    width: 150,
    height: 150,
    imageClasses: "modal-trigger-image"
};